# Generated by Django 3.2.2 on 2021-05-10 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210510_2031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-is_superuser', '-is_staff', 'last_name', 'first_name'], 'verbose_name': 'custom user', 'verbose_name_plural': 'custom users'},
        ),
    ]
