# Generated by Django 3.2.2 on 2021-05-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Large Juice'", max_length=50, unique=True)),
                ('website', models.URLField(blank=True, help_text='full URL for website homepage')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Vape Club'", max_length=50, unique=True)),
                ('website', models.URLField(blank=True, help_text='full URL for website homepage')),
                ('location', models.CharField(choices=[('GBR', 'United Kingdom of Great Britain and Northern Ireland'), ('USA', 'United States of America')], default='GBR', help_text='where the supplier ships products from', max_length=3)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.CheckConstraint(check=models.Q(('name', ''), _negated=True), name='companies_supplier_name_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.CheckConstraint(check=models.Q(('location', ''), _negated=True), name='companies_supplier_location_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.CheckConstraint(check=models.Q(('location__in', ['GBR', 'USA'])), name='companies_supplier_location_valid'),
        ),
        migrations.AddConstraint(
            model_name='brand',
            constraint=models.CheckConstraint(check=models.Q(('name', ''), _negated=True), name='companies_brand_name_not_blank'),
        ),
    ]
