# Generated by Django 3.2.2 on 2021-05-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210513_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='is_shortfill',
            field=models.BooleanField(default=False, verbose_name='shortfill'),
        ),
    ]
